apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxhelloworld
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxhelloworld
  template:
    metadata:
      labels:
        app: nginxhelloworld
    spec:
      containers:
      - name: nginxhelloworld
        image: nginxdemos/hello
        ports:
        - containerPort: 80